name: example-environment
channels:
  - conda-forge
dependencies:
  - bqplot=0.12.32
  - pyplot
  - Tooltip
  - matplotlib=3.5.0
  - numpy=1.20.3
  - ipywidgets=7.6.5
  - pandas=1.3.5
  - Point
  - GeoDataFrame
  - contextily=1.2.0
